{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ddb37272",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "\n",
    "# 1. UI Page configurations\n",
    "st.set_page_config(page_title=\"UniUyo EE15 Structural Integrity App\", layout=\"centered\")\n",
    "st.title(\"🧱 Automated Concrete Bridge Deck Inspection System\")\n",
    "st.caption(\"GET 324: Artificial Intelligence, Machine Learning and Convergent Technologies\")\n",
    "st.write(\"**Group Assignment Task EE15:** Concrete Bridge Deck Crack Detection\")\n",
    "\n",
    "# 2. Set strict structural inspection categories\n",
    "CLASS_0 = \"Non-Cracked (Structurally Sound)\"\n",
    "CLASS_1 = \"Cracked (Anomalies Detected / Maintenance Required)\"\n",
    "\n",
    "# 3. Cached resource loader to prevent container out-of-memory errors\n",
    "@st.cache_resource\n",
    "def load_uniuyo_model():\n",
    "    return tf.keras.models.load_model('model.h5')\n",
    "\n",
    "try:\n",
    "    model = load_uniuyo_model()\n",
    "    st.success(\"🤖 Deep Learning Diagnostic Model Connected Successfully!\")\n",
    "except Exception as e:\n",
    "    st.error(f\"Execution Error: Could not find 'model.h5' file in repository. Details: {e}\")\n",
    "\n",
    "# 4. File submission handler widget\n",
    "uploaded_file = st.file_uploader(\"Upload concrete surface photograph...\", type=[\"jpg\", \"jpeg\", \"png\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    # Render graphic component safely\n",
    "    image = Image.open(uploaded_file)\n",
    "    st.image(image, caption=\"Submitted Surface Specimen\", use_container_width=True)\n",
    "    \n",
    "    st.write(\"🔍 Running computerized visual feature extraction tracking line anomalies...\")\n",
    "    \n",
    "    # Matrix normalization preprocessing pipeline\n",
    "    img_resized = image.resize((224, 224))\n",
    "    img_array = tf.keras.utils.img_to_array(img_resized)\n",
    "    img_batch = np.expand_dims(img_array, axis=0)\n",
    "    \n",
    "    # Generate predictive mathematical matrix output scores\n",
    "    prediction = model.predict(img_batch)\n",
    "    \n",
    "    st.divider()\n",
    "    \n",
    "    # Binary conditional activation mapping threshold\n",
    "    if prediction >= 0.5:\n",
    "        confidence = prediction * 100\n",
    "        st.error(f\"🚨 **Structural Inspection Status: {CLASS_1}**\")\n",
    "        st.metric(label=\"Crack Probability Index\", value=f\"{confidence:.2f}%\")\n",
    "    else:\n",
    "        confidence = (1 - prediction) * 100\n",
    "        st.success(f\"🍏 **Structural Inspection Status: {CLASS_0}**\")\n",
    "        st.metric(label=\"Structural Reliability Margin\", value=f\"{confidence:.2f}%\")\n",
    "\n",
    "st.divider()\n",
    "st.info(\"📌 **Submission Specifications:** Faculty of Engineering, Department of Computer Engineering, University of Uyo.\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
